"""Initial migration

Revision ID: 1a9733c78095
Revises: 
Create Date: 2025-11-27 20:36:00.961979

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a9733c78095"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "RETAIL",
                "WHOLESALE",
                "FOOD_SERVICE",
                "ONLINE",
                "DISTRIBUTOR",
                name="customertype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="customerstatus"),
            nullable=False,
        ),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column(
            "business_registration_number",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("credit_limit_rm", sa.Integer(), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("is_key_account", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_customer_code"),
        "customers",
        ["customer_code"],
        unique=True,
    )
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "FINISHED_GOODS",
                "RAW_MATERIALS",
                "PACKAGING",
                "BEVERAGES",
                "PROTEINS",
                "VEGETABLES",
                "GRAINS",
                "SAUCES_CONDIMENTS",
                name="productcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PHASE_IN",
                "PHASE_OUT",
                "DISCONTINUED",
                name="productstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "base_uom",
            sa.Enum(
                "KG",
                "GRAM",
                "LITRE",
                "ML",
                "PIECE",
                "PACK",
                "BOX",
                "CASE",
                name="unitofmeasure",
            ),
            nullable=False,
        ),
        sa.Column(
            "pack_size", sa.Numeric(precision=10, scale=3), nullable=True
        ),
        sa.Column(
            "standard_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "selling_price", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column("supplier_lead_time", sa.Integer(), nullable=True),
        sa.Column("safety_stock_days", sa.Integer(), nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("is_perishable", sa.Boolean(), nullable=False),
        sa.Column("storage_temperature", sa.String(length=50), nullable=True),
        sa.Column("has_bom", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "suppliers",
        sa.Column("supplier_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "RAW_MATERIAL",
                "PACKAGING",
                "EQUIPMENT",
                "SERVICE",
                "LOGISTICS",
                name="suppliertype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "BLACKLISTED",
                name="supplierstatus",
            ),
            nullable=False,
        ),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column(
            "business_registration_number",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=True),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.Column("quality_rating", sa.String(length=10), nullable=True),
        sa.Column("halal_certified", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_id"), "suppliers", ["id"], unique=False)
    op.create_index(
        op.f("ix_suppliers_supplier_code"),
        "suppliers",
        ["supplier_code"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "SOP_LEADER", "VIEWER", name="userrole"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.create_table(
        "aop_targets",
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column(
            "period",
            sa.Enum("MONTHLY", "QUARTERLY", "YEARLY", name="aopperiod"),
            nullable=False,
        ),
        sa.Column("period_start_date", sa.Date(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("scope_type", sa.String(length=50), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "target_category",
            sa.Enum(
                "SALES_REVENUE",
                "SALES_VOLUME",
                "GROSS_MARGIN",
                "MARKET_SHARE",
                "NEW_CUSTOMERS",
                "COST_REDUCTION",
                "INVENTORY_TURNOVER",
                name="aopcategory",
            ),
            nullable=False,
        ),
        sa.Column("target_name", sa.String(length=255), nullable=False),
        sa.Column("target_description", sa.Text(), nullable=True),
        sa.Column(
            "target_revenue_rm",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_volume_units",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
        ),
        sa.Column(
            "target_margin_rm",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_margin_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_market_share_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("target_new_customers", sa.Integer(), nullable=True),
        sa.Column(
            "target_customer_retention_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_inventory_turnover",
            sa.Numeric(precision=6, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_cost_reduction_rm",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column(
            "target_service_level_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "actual_revenue_rm",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "actual_volume_units",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "actual_margin_rm",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "actual_margin_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "ytd_achievement_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "forecast_achievement_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "variance_to_target_rm",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "variance_to_target_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("risk_factors", sa.Text(), nullable=True),
        sa.Column("mitigation_actions", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "UNDER_REVIEW",
                "APPROVED",
                "LOCKED",
                "REVISED",
                name="aopstatus",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("last_review_date", sa.Date(), nullable=True),
        sa.Column("next_review_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aop_targets_fiscal_year"),
        "aop_targets",
        ["fiscal_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aop_targets_id"), "aop_targets", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_aop_targets_product_id"),
        "aop_targets",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "bill_of_materials",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DRAFT", "INACTIVE", name="bomstatus"),
            nullable=False,
        ),
        sa.Column(
            "batch_size", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "yield_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column("production_time_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "labor_cost_per_batch",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
        ),
        sa.Column(
            "overhead_cost_per_batch",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "version", name="uix_bom_product_version"
        ),
    )
    op.create_index(
        op.f("ix_bill_of_materials_id"),
        "bill_of_materials",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bill_of_materials_product_id"),
        "bill_of_materials",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "demand_forecasts",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_period_start", sa.Date(), nullable=False),
        sa.Column("forecast_period_end", sa.Date(), nullable=False),
        sa.Column(
            "forecast_method",
            sa.Enum(
                "MANUAL",
                "MOVING_AVERAGE",
                "EXPONENTIAL_SMOOTHING",
                "SARIMA",
                "LINEAR_REGRESSION",
                "PROPHET",
                "ENSEMBLE",
                name="forecastmethod",
            ),
            nullable=False,
        ),
        sa.Column(
            "forecast_type",
            sa.Enum(
                "BASELINE", "PROMOTIONAL", "CONSENSUS", name="forecasttype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_REVIEW",
                "APPROVED",
                "LOCKED",
                name="forecaststatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "baseline_demand",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "promotional_uplift",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "final_forecast", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "actual_demand", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "absolute_error", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "percentage_error", sa.Numeric(precision=8, scale=4), nullable=True
        ),
        sa.Column(
            "confidence_level", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "forecast_bias", sa.Numeric(precision=8, scale=4), nullable=False
        ),
        sa.Column(
            "seasonal_factor", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.Column(
            "trend_factor", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.Column("marketing_events", sa.Text(), nullable=True),
        sa.Column("external_factors", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("forecast_lag", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_demand_forecasts_forecast_date"),
        "demand_forecasts",
        ["forecast_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_demand_forecasts_id"),
        "demand_forecasts",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_demand_forecasts_product_id"),
        "demand_forecasts",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "marketing_calendar",
        sa.Column("event_name", sa.String(length=255), nullable=False),
        sa.Column("event_code", sa.String(length=50), nullable=False),
        sa.Column(
            "promo_type",
            sa.Enum(
                "DISCOUNT",
                "BOGO",
                "BUNDLE",
                "VOLUME_DISCOUNT",
                "SEASONAL",
                "LOYALTY",
                "NEW_PRODUCT",
                "CLEARANCE",
                name="promotype",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column(
            "promo_channel",
            sa.Enum(
                "ALL_CHANNELS",
                "RETAIL",
                "ONLINE",
                "WHOLESALE",
                "FOOD_SERVICE",
                name="promochannel",
            ),
            nullable=False,
        ),
        sa.Column("target_customer_segments", sa.Text(), nullable=True),
        sa.Column("geographic_scope", sa.String(length=255), nullable=False),
        sa.Column(
            "discount_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "discount_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "minimum_purchase_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "maximum_discount_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "volume_threshold_1",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "volume_discount_1",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "volume_threshold_2",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "volume_discount_2",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "marketing_budget_rm",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "expected_roi_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "expected_uplift_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "expected_cannibalization_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "baseline_volume_impact",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "ACTIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                name="promostatus",
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "actual_sales_volume",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
        ),
        sa.Column(
            "actual_sales_value_rm",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column(
            "actual_uplift_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column(
            "actual_roi_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("success_criteria", sa.Text(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marketing_calendar_end_date"),
        "marketing_calendar",
        ["end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketing_calendar_event_code"),
        "marketing_calendar",
        ["event_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_marketing_calendar_id"),
        "marketing_calendar",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketing_calendar_start_date"),
        "marketing_calendar",
        ["start_date"],
        unique=False,
    )
    op.create_table(
        "sales_actuals",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=False),
        sa.Column(
            "quantity_sold", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "unit_price", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "gross_sales_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "net_sales_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "unit_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "total_cost", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "gross_margin_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "gross_margin_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "sales_channel",
            sa.Enum(
                "RETAIL",
                "WHOLESALE",
                "ONLINE",
                "FOOD_SERVICE",
                "DISTRIBUTOR",
                "DIRECT_SALES",
                name="saleschannel",
            ),
            nullable=False,
        ),
        sa.Column("sales_rep_id", sa.Integer(), nullable=True),
        sa.Column("promotion_code", sa.String(length=50), nullable=True),
        sa.Column("is_promotional_sale", sa.Boolean(), nullable=False),
        sa.Column("delivery_location", sa.String(length=255), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column(
            "shipping_cost", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_rep_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_actuals_customer_id"),
        "sales_actuals",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_actuals_id"), "sales_actuals", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_actuals_invoice_number"),
        "sales_actuals",
        ["invoice_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_actuals_product_id"),
        "sales_actuals",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_actuals_transaction_date"),
        "sales_actuals",
        ["transaction_date"],
        unique=False,
    )
    op.create_table(
        "sales_orders",
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("external_order_ref", sa.String(length=100), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("requested_delivery_date", sa.Date(), nullable=False),
        sa.Column("confirmed_delivery_date", sa.Date(), nullable=True),
        sa.Column("actual_delivery_date", sa.Date(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity_ordered",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "quantity_shipped",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "quantity_remaining",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "unit_price", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "total_order_value",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
        ),
        sa.Column(
            "order_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "IN_PRODUCTION",
                "READY_TO_SHIP",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "RETURNED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "PAID",
                "PARTIAL",
                "OVERDUE",
                "REFUNDED",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "sales_channel",
            sa.Enum(
                "RETAIL",
                "WHOLESALE",
                "ONLINE",
                "FOOD_SERVICE",
                "DISTRIBUTOR",
                "DIRECT_SALES",
                name="saleschannel",
            ),
            nullable=False,
        ),
        sa.Column("sales_rep_id", sa.Integer(), nullable=True),
        sa.Column("priority_level", sa.String(length=20), nullable=False),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("requires_cold_chain", sa.Boolean(), nullable=False),
        sa.Column("production_start_date", sa.Date(), nullable=True),
        sa.Column("production_completion_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_rep_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_orders_customer_id"),
        "sales_orders",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_id"), "sales_orders", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_orders_order_date"),
        "sales_orders",
        ["order_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_order_number"),
        "sales_orders",
        ["order_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sales_orders_product_id"),
        "sales_orders",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "stock_movements",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "RECEIPT",
                "ISSUE",
                "TRANSFER",
                "ADJUSTMENT",
                "RETURN",
                "PRODUCTION",
                "SALE",
                "WASTAGE",
                name="movementtype",
            ),
            nullable=False,
        ),
        sa.Column("movement_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "COMPLETED", "CANCELLED", name="movementstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "from_location",
            sa.Enum(
                "MAIN_WAREHOUSE",
                "COLD_STORAGE",
                "FROZEN_STORAGE",
                "DRY_STORAGE",
                "PRODUCTION_FLOOR",
                "RETAIL_OUTLET",
                name="stocklocation",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_location",
            sa.Enum(
                "MAIN_WAREHOUSE",
                "COLD_STORAGE",
                "FROZEN_STORAGE",
                "DRY_STORAGE",
                "PRODUCTION_FLOOR",
                "RETAIL_OUTLET",
                name="stocklocation",
            ),
            nullable=True,
        ),
        sa.Column(
            "unit_cost", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "total_cost", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("related_order_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_id"), "stock_movements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_movement_date"),
        "stock_movements",
        ["movement_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_product_id"),
        "stock_movements",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "stock_on_hand",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            sa.Enum(
                "MAIN_WAREHOUSE",
                "COLD_STORAGE",
                "FROZEN_STORAGE",
                "DRY_STORAGE",
                "PRODUCTION_FLOOR",
                "RETAIL_OUTLET",
                name="stocklocation",
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_on_hand",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "reserved_quantity",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "available_quantity",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "average_unit_cost",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "total_value", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "RESERVED",
                "DAMAGED",
                "EXPIRED",
                "QUARANTINE",
                name="stockstatus",
            ),
            nullable=False,
        ),
        sa.Column("last_movement_date", sa.Date(), nullable=True),
        sa.Column("days_since_last_movement", sa.Integer(), nullable=False),
        sa.Column("earliest_expiry_date", sa.Date(), nullable=True),
        sa.Column("days_to_expiry", sa.Integer(), nullable=True),
        sa.Column("is_near_expiry", sa.Boolean(), nullable=False),
        sa.Column(
            "safety_stock_level",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "reorder_point", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "max_stock_level", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column("last_count_date", sa.Date(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_on_hand_id"), "stock_on_hand", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_on_hand_product_id"),
        "stock_on_hand",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "bom_components",
        sa.Column("bom_id", sa.Integer(), nullable=False),
        sa.Column("component_product_id", sa.Integer(), nullable=False),
        sa.Column(
            "component_type",
            sa.Enum(
                "RAW_MATERIAL",
                "PACKAGING",
                "SUB_ASSEMBLY",
                name="componenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_per_batch",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "wastage_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "unit_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("substitute_product_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bom_id"],
            ["bill_of_materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["component_product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substitute_product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bom_components_bom_id"),
        "bom_components",
        ["bom_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bom_components_component_product_id"),
        "bom_components",
        ["component_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bom_components_id"), "bom_components", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bom_components_id"), table_name="bom_components")
    op.drop_index(
        op.f("ix_bom_components_component_product_id"),
        table_name="bom_components",
    )
    op.drop_index(
        op.f("ix_bom_components_bom_id"), table_name="bom_components"
    )
    op.drop_table("bom_components")
    op.drop_index(
        op.f("ix_stock_on_hand_product_id"), table_name="stock_on_hand"
    )
    op.drop_index(op.f("ix_stock_on_hand_id"), table_name="stock_on_hand")
    op.drop_table("stock_on_hand")
    op.drop_index(
        op.f("ix_stock_movements_product_id"), table_name="stock_movements"
    )
    op.drop_index(
        op.f("ix_stock_movements_movement_date"), table_name="stock_movements"
    )
    op.drop_index(op.f("ix_stock_movements_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(
        op.f("ix_sales_orders_product_id"), table_name="sales_orders"
    )
    op.drop_index(
        op.f("ix_sales_orders_order_number"), table_name="sales_orders"
    )
    op.drop_index(
        op.f("ix_sales_orders_order_date"), table_name="sales_orders"
    )
    op.drop_index(op.f("ix_sales_orders_id"), table_name="sales_orders")
    op.drop_index(
        op.f("ix_sales_orders_customer_id"), table_name="sales_orders"
    )
    op.drop_table("sales_orders")
    op.drop_index(
        op.f("ix_sales_actuals_transaction_date"), table_name="sales_actuals"
    )
    op.drop_index(
        op.f("ix_sales_actuals_product_id"), table_name="sales_actuals"
    )
    op.drop_index(
        op.f("ix_sales_actuals_invoice_number"), table_name="sales_actuals"
    )
    op.drop_index(op.f("ix_sales_actuals_id"), table_name="sales_actuals")
    op.drop_index(
        op.f("ix_sales_actuals_customer_id"), table_name="sales_actuals"
    )
    op.drop_table("sales_actuals")
    op.drop_index(
        op.f("ix_marketing_calendar_start_date"),
        table_name="marketing_calendar",
    )
    op.drop_index(
        op.f("ix_marketing_calendar_id"), table_name="marketing_calendar"
    )
    op.drop_index(
        op.f("ix_marketing_calendar_event_code"),
        table_name="marketing_calendar",
    )
    op.drop_index(
        op.f("ix_marketing_calendar_end_date"), table_name="marketing_calendar"
    )
    op.drop_table("marketing_calendar")
    op.drop_index(
        op.f("ix_demand_forecasts_product_id"), table_name="demand_forecasts"
    )
    op.drop_index(
        op.f("ix_demand_forecasts_id"), table_name="demand_forecasts"
    )
    op.drop_index(
        op.f("ix_demand_forecasts_forecast_date"),
        table_name="demand_forecasts",
    )
    op.drop_table("demand_forecasts")
    op.drop_index(
        op.f("ix_bill_of_materials_product_id"), table_name="bill_of_materials"
    )
    op.drop_index(
        op.f("ix_bill_of_materials_id"), table_name="bill_of_materials"
    )
    op.drop_table("bill_of_materials")
    op.drop_index(op.f("ix_aop_targets_product_id"), table_name="aop_targets")
    op.drop_index(op.f("ix_aop_targets_id"), table_name="aop_targets")
    op.drop_index(op.f("ix_aop_targets_fiscal_year"), table_name="aop_targets")
    op.drop_table("aop_targets")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_supplier_code"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_customer_code"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
