"""add_reorder_level_to_product

Revision ID: 392ac3c5e398
Revises: 1a9733c78095
Create Date: 2025-11-28 02:51:41.699346

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "392ac3c5e398"
down_revision = "1a9733c78095"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "reorder_level", sa.Numeric(precision=12, scale=4), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "reorder_level")
    # ### end Alembic commands ###
